<?php
/**
 * @category   CLS
 * @package    CustomerAdvanced
 * @copyright  Copyright (c) 2015 Classy Llama Studios, LLC (http://www.classyllama.com)
 * @license    See LICENSE_CLS.txt for license details
 */
?>

<?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>

<?php
/* @var $captcha Mage_Core_Model_Captcha_Zend */

$_idPrefix = $this->getIdPrefix();
if (!empty($_idPrefix)) {
    $_idPrefix .= '_';
}

$_formId = $_idPrefix . $this->getFormId();
?>
<?php $captcha = $this->getCaptchaModel() ?>
<li id="captcha-input-box-<?php echo $_formId?>">
    <label for="captcha_<?php echo $_formId ?>" class="required"><em>*</em><?php echo $this->__('Please type the letters below')?></label>
    <div class="input-box captcha">
        <input name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $_formId?>]" type="text" class="input-text required-entry" id="captcha_<?php echo $_formId ?>" />
    </div>
</li>
<li>
    <div class="captcha-image" id="captcha-image-box-<?php echo $_formId?>">
        <img class="captcha-reload" src="<?php echo $this->getSkinUrl('images/reload.png') ?>" alt="<?php echo $this->__('Reload captcha') ?>" onclick="$('<?php echo $_formId?>').captcha.refresh(this)">
        <img id="<?php echo $_formId ?>" class="captcha-img" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>"/>
        <?php if ($captcha->isCaseSensitive()) :?>
            <div class="captcha-note">
                <?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
            </div>
        <?php endif; ?>
    </div>
    <script type="text/javascript">//<![CDATA[
        $('<?php echo $_formId ?>').captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $_formId ?>');
        //]]></script>
</li>

