<?php
/**
 * Crius
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt
 *
 * @category   Crius
 * @package    Crius_Rac
 * @copyright  Copyright (c) 2011 Crius (http://www.criuscommerce.com)
 * @license    http://www.criuscommerce.com/CRIUS-LICENSE.txt
 */
?>
<?php
/**
 * Password form for success page
 *
 * @see Crius_Rac_Block_Register
 */
?>
<?php if ($this->canRegister()): ?>
<div class="checkout-success-register opc">
    <form id="checkout-success-register">
        <h2 class="sub-title"><?php echo $this->__('Register with us for future convenience:') ?></h2>
        <ul class="ul">
            <li><?php echo $this->__('Fast and easy check out') ?></li>
            <li><?php echo $this->__('Easy access to your order history and status') ?></li>
        </ul>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set" id="register-buttons-container">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <button id="register-submit" type="submit" title="<?php echo $this->__('Register') ?>" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
            <span class="please-wait" id="register-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[        
        var racForm = new RegisterAfterCheckout('checkout-success-register', '<?php echo $this->getUrl('rac/ajax/register', array('_secure' => true)) ?>');
    //]]>
    </script>
</div>
<?php endif ?>
