{{block type="cms/block" block_id="nucleus-elements-navigation"}}

<ul class="pattern-nav-secondary">
    <li>Elements: </li>
    <li><a href="#hero-center">Hero - Center</a></li>
    <li><a href="#hero-center-33">Hero - Center 33%</a></li>
    <li><a href="#hero-center-50">Hero - Center 50%</a></li>
    <li><a href="#hero-center-66">Hero - Center 66%</a></li>
    <li><a href="#hero-cta">Hero - Call to Action</a></li>
    <li><a href="#hero-cta-light">Hero - Call to Action Light</a></li>
    <li><a href="#hero-dark">Hero - Dark</a></li>
    <li><a href="#hero-left">Hero - Left</a></li>
    <li><a href="#hero-left-50">Hero - Left 50%</a></li>
    <li><a href="#hero-left-66">Hero - Left 66%</a></li>
    <li><a href="#hero-right">Hero - Right</a></li>
    <li><a href="#hero-right-33">Hero - Right 33%</a></li>
    <li><a href="#hero-right-50">Hero - Right 50%</a></li>
    <li><a href="#hero-right-66">Hero - Right 66%</a></li>
    <li><a href="#hero-light">Hero - Light</a></li>

</ul>


<h2 id="hero-center" class="pattern-title">Hero - Center</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-center</strong></p>
{{block type="cms/block" block_id="nucleus-hero-center"}}

<h2 id="hero-center-33" class="pattern-title">Hero - Center 33%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-center-33</strong></p>
{{block type="cms/block" block_id="nucleus-hero-center-33"}}

<h2 id="hero-center-50" class="pattern-title">Hero - Center 50%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-center-50</strong></p>
{{block type="cms/block" block_id="nucleus-hero-center-50"}}

<h2 id="hero-center-66" class="pattern-title">Hero - Center 66%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-center-66</strong></p>
{{block type="cms/block" block_id="nucleus-hero-center-66"}}

<h2 id="hero-cta" class="pattern-title">Hero - Call to Action</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-cta</strong></p>
{{block type="cms/block" block_id="nucleus-hero-cta"}}

<h2 id="hero-cta-light" class="pattern-title">Hero - Call to Action Light</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-cta-light</strong></p>
{{block type="cms/block" block_id="nucleus-hero-cta-light"}}

<h2 id="hero-dark" class="pattern-title">Hero - Dark</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-dark</strong></p>
{{block type="cms/block" block_id="nucleus-hero-dark"}}

<h2 id="hero-left" class="pattern-title">Hero - Left</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-left</strong></p>
{{block type="cms/block" block_id="nucleus-hero-left"}}

<h2 id="hero-left-33" class="pattern-title">Hero - Left 33%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-left-33</strong></p>
{{block type="cms/block" block_id="nucleus-hero-left-33"}}

<h2 id="hero-left-50" class="pattern-title">Hero - Left 50%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-left-50</strong></p>
{{block type="cms/block" block_id="nucleus-hero-left-50"}}

<h2 id="hero-left-66" class="pattern-title">Hero - Left 66%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-left-66</strong></p>
{{block type="cms/block" block_id="nucleus-hero-left-66"}}

<h2 id="hero-right" class="pattern-title">Hero - Right</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-right</strong></p>
{{block type="cms/block" block_id="nucleus-hero-right"}}

<h2 id="hero-right-33" class="pattern-title">Hero - Right 33%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-right-33</strong></p>
{{block type="cms/block" block_id="nucleus-hero-right-33"}}

<h2 id="hero-right-50" class="pattern-title">Hero - Right 50%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-right-50</strong></p>
{{block type="cms/block" block_id="nucleus-hero-right-50"}}

<h2 id="hero-right-66" class="pattern-title">Hero - Right 66%</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-right-66</strong></p>
{{block type="cms/block" block_id="nucleus-hero-right-66"}}

<h2 id="hero-light" class="pattern-title">Hero - Light</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-hero-light</strong></p>
{{block type="cms/block" block_id="nucleus-hero-light"}}
