{{block type="cms/block" block_id="nucleus-elements-navigation"}}

<ul class="pattern-nav-secondary">
    <li>Elements: </li>
    <li><a href="#grid-box-half-left">Grid Box - Half Left</a></li>
    <li><a href="#grid-box-half-right">Grid Box - Half Right</a></li>
    <li><a href="#grid-box-third-left">Grid Box - Third Left</a></li>
    <li><a href="#grid-box-third-right">Grid Box - Third Right</a></li>
    <li><a href="#ad">Ad</a></li>
    <li><a href="#ad-image">Ad - Image Only</a></li>
    <li><a href="#set-3-text">Set 3 Text</a></li>
    <li><a href="#set-3-images">Set 3 Images</a></li>
    <li><a href="#set-4-text">Set 4 Text</a></li>
    <li><a href="#set-4-images">Set 4 Images</a></li>
    <li><a href="#block">Block</a></li>
    <li><a href="#block-toggle">Block Toggle</a></li>
    <li><a href="#story">Story</a></li>
</ul>


<h2 id="gridbox-half-left" class="pattern-title">Grid Box - Half Left</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-grid-box-half-left</strong></p>
{{block type="cms/block" block_id="nucleus-grid-box-half-left"}}

<h2 id="grid-box-half-right" class="pattern-title">Grid Box - Half Right</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-grid-box-half-right</strong></p>
{{block type="cms/block" block_id="nucleus-grid-box-half-right"}}

<h2 id="grid-box-third-left" class="pattern-title">Grid Box - Third Left</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-grid-box-third-left</strong></p>
{{block type="cms/block" block_id="nucleus-grid-box-third-left"}}

<h2 id="grid-box-third-right" class="pattern-title">Grid Box - Third Right</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-grid-box-third-right</strong></p>
{{block type="cms/block" block_id="nucleus-grid-box-third-right"}}

<h2 id="ad" class="pattern-title">Ad</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-ad</strong></p>
{{block type="cms/block" block_id="nucleus-ad"}}

<h2 id="ad-image" class="pattern-title">Ad - Image Only</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-ad-image-only</strong></p>
{{block type="cms/block" block_id="nucleus-ad-image-only"}}

<h2 id="set-3-text" class="pattern-title">Set 3 - Text</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-set-3-text</strong></p>
{{block type="cms/block" block_id="nucleus-set-3-text"}}

<h2 id="set-3-images" class="pattern-title">Set 3 - Images</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-set-3-images</strong></p>
{{block type="cms/block" block_id="nucleus-set-3-images"}}

<h2 id="set-4-text" class="pattern-title">Set 4 - Text</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-set-4-text</strong></p>
{{block type="cms/block" block_id="nucleus-set-4-text"}}

<h2 id="set-4-images" class="pattern-title">Set 4 - Images</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-set-4-images</strong></p>
{{block type="cms/block" block_id="nucleus-set-4-images"}}

<h2 id="block" class="pattern-title">Block</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-block</strong></p>
{{block type="cms/block" block_id="nucleus-block"}}

<h2 id="block-toggle" class="pattern-title">Block Toggle</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-block-toggle</strong></p>
{{block type="cms/block" block_id="nucleus-block-toggle"}}

<h2 id="story" class="pattern-title">Story</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-story</strong></p>
{{block type="cms/block" block_id="nucleus-story"}}