{{block type="cms/block" block_id="nucleus-elements-navigation"}}

<ul class="pattern-nav-secondary">
    <li>Elements: </li>
    <li><a href="#accordion">Accordion</a></li>
    <li><a href="#tabs">Tabs</a></li>
    <li><a href="#modal">Modal</a></li>
</ul>


<h2 id="accordion" class="pattern-title">Accordion</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-accordion</strong></p>
<p>The Accordion element scales down to a collapsible/expandable interface at smaller screen sizes.</p>
{{block type="cms/block" block_id="nucleus-accordion"}}

<h2 id="tabs" class="pattern-title">Tabs</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-tabs</strong></p>
{{block type="cms/block" block_id="nucleus-tabs"}}

<h2 id="modal" class="pattern-title">Modal</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-modal</strong></p>
<p>The Modal element defines content that will open in a modal window when the trigger button is activated.</p>
{{block type="cms/block" block_id="nucleus-modal"}}