{{block type="cms/block" block_id="nucleus-elements-navigation"}}

<ul class="pattern-nav-secondary">
    <li>Elements: </li>
    <li><a href="#masthead">Masthead</a></li>
    <li><a href="#lead">Lead</a></li>
    <li><a href="#expand">Expand</a></li>
    <li><a href="#stats">Stats</a></li>
    <li><a href="#stats-horizontal">Stat List Horizontal</a></li>
    <li><a href="#stats-vertical">Stat List Vertical</a></li>
    <li><a href="#tooltip-top-left">Tooltip - Top Left</a></li>
    <li><a href="#tooltip-bottom-left">Tooltip - Bottom Left</a></li>
    <li><a href="#promo-strap-text">Promo Strap - Text</a></li>
    <li><a href="#promo-strap-link">Promo Strap - Link</a></li>
</ul>


<h2 id="masthead" class="pattern-title">Masthead</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-masthead</strong></p>
{{block type="cms/block" block_id="nucleus-masthead"}}

<h2 id="lead" class="pattern-title">Lead</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-lead</strong></p>
{{block type="cms/block" block_id="nucleus-lead"}}

<h2 id="expand" class="pattern-title">Expand</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-expand</strong></p>
<p>The Expand element defines a block of content that is hidden initially, until the trigger button is activated.</p>
{{block type="cms/block" block_id="nucleus-expand"}}

<h2 id="stats" class="pattern-title">Stat</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-stat-single</strong></p>
{{block type="cms/block" block_id="nucleus-stat-single"}}

<h2 id="stats-horizontal" class="pattern-title">Stat List Horizontal</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-stat-list-horizontal</strong></p>
{{block type="cms/block" block_id="nucleus-stat-list-horizontal"}}

<h2 id="stats-vertical" class="pattern-title">Stat List Vertical</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-stat-list-vertical</strong></p>
{{block type="cms/block" block_id="nucleus-stat-list-vertical"}}

<h2 id="tooltip-bottom-left" class="pattern-title">Tooltip - Bottom Left</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-tooltip-bottom-left</strong></p>
<p>Hover your cursor over the trigger text to display the tooltip.</p>
{{block type="cms/block" block_id="nucleus-tooltip-bottom-left"}}

<h2 id="tooltip-top-left" class="pattern-title">Tooltip - Top Left</h2>
<p class="pattern-info">Use this element by copying the static block titled <strong>nucleus-tooltip-top-left</strong></p>
<p>Hover your cursor over the trigger text to display the tooltip.</p>
{{block type="cms/block" block_id="nucleus-tooltip-top-left"}}

<h2 id="promo-strap-text" class="pattern-title">Promo Strap - Text</h2>
<p class=“pattern-info”>Use this element by copying the static block titled <strong>nucleus-promo-strap-text</strong></p>
{{block type="cms/block" block_id="nucleus-promo-strap-text"}}

<h2 id="promo-strap-link" class="pattern-title">Promo Strap - Link</h2>
<p class=“pattern-info”>Use this element by copying the static block titled <strong>nucleus-promo-strap-link</strong></p>
{{block type="cms/block" block_id="nucleus-promo-strap-link"}}
