<?php
/**
 * @category   CLS
 * @package    Widgets
 * @copyright  Copyright (c) 2015 Classy Llama Studios, LLC (http://www.classyllama.com)
 * @license    See LICENSE_CLS.txt for license details
 */
?>
<?php
/**
 * Sub-category list template
 *
 * @see CLS_Widgets_Block_Widget_Catalog_Product_Carousel
 */

// By default is a percentage of item width, but stored here so it can be arbitrarily changed
$_itemImgSize = $this->getItemImgSize();
$_index = $this->helper('cls_widgets')->getWidgetIndex();
$_productCollection = $this->getProductCollection();
?>
<script type="text/javascript">

    if (bp === undefined) {
        var bp = {
            xsmall: 479,
            medium: 770,
            large: 979
        };
    }

    jQuery(document).ready(function (jQ) {
        jQ('#widget_carousel_<?php echo $_index ?> .owl-carousel').owlCarousel({
            theme: 'lcp-theme',
            autoPlay: <?php echo ($this->getAutostart()) ? $this->getTimeout() : 'false' ?>,
            stopOnHover: <?php echo ($this->getHoverPause()) ? 'true' : 'false' ?>,
            navigation: <?php echo ($this->getIncludePrevNext()) ? 'true' : 'false' ?>,
            navigationText: ['<span class="slide-arrow"></span>', '<span class="slide-arrow"></span>'],
            pagination: <?php echo ($this->getIncludePager()) ? 'true' : 'false' ?>,
            paginationNumbers: <?php echo ($this->getNumbersInPager()) ? 'true' : 'false' ?>,
            items: <?php echo $this->getItemsPerSlide() ?>,
            itemsDesktop: false, // Don't set a value for desktop as it will inherit from "items"
            <?php if ((int) $this->getItemsPerSlideLarge()): ?>
                itemsDesktopSmall: [bp.large, <?php echo (int) $this->getItemsPerSlideLarge() ?>],
            <?php else: ?>
                itemsDesktopSmall: [bp.large, 4],
            <?php endif; ?>
            <?php if ((int) $this->getItemsPerSlideMedium()): ?>
                itemsTablet: [bp.medium, <?php echo (int) $this->getItemsPerSlideMedium() ?>],
            <?php else: ?>
                itemsTablet: [bp.medium, 3],
            <?php endif; ?>
            <?php if ((int) $this->getItemsPerSlideSmall()): ?>
                itemsMobile: [bp.xsmall, <?php echo (int) $this->getItemsPerSlideSmall() ?>],
            <?php else: ?>
                itemsMobile: [bp.xsmall,2],
            <?php endif; ?>
            scrollPerPage: <?php echo ($this->getScrollPerPage()) ? 'true' : 'false' ?>,
            afterInit : function(){
                var that = this

                // Move next/previous buttons
                that.owlControls.find('.owl-buttons').prependTo(jQ('#widget_carousel_<?php echo $_index ?> .owl-carousel'))
            }
        });
    });
</script>

<div class="widget widget-carousel" id="widget_carousel_<?php echo $_index ?>">
<?php if ($_title = $this->getDisplayTitle()): ?>
    <h3><?php echo $this->__($_title) ?></h3>
<?php endif; ?>
<?php if ($_productCollection && $_productCollection->count() > 0): ?>
    <div class="owl-carousel">
        <?php foreach ($_productCollection as $_product): ?>
            <div>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_itemImgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="item-image" />
                </a>
                <h4><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a></h4>
                <?php echo $this->getPriceHtml($_product, true) ?>
            </div>
        <?php endforeach; ?>
   </div>
<?php endif; ?>
</div>
