<?php
/*////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\   FME Jobs extension  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\ NOTICE OF LICENSE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                                                                   ///////
 \\\\\\\ This source file is subject to the Open Software License (OSL 3.0)\\\\\\\
 ///////   that is bundled with this package in the file LICENSE.txt.      ///////
 \\\\\\\   It is also available through the world-wide-web at this URL:    \\\\\\\
 ///////          http://opensource.org/licenses/osl-3.0.php               ///////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                      * @category   FME                            ///////
 \\\\\\\                      * @package    Jobs                           \\\\\\\
 ///////    * @author     Kaleem Ullah Khan <kaleem.ullah@unitedsol.net>   ///////
 \\\\\\\                                                                   \\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\* @copyright  Copyright 2010 © free-magentoextensions.com All right reserved\\\
 /////////////////////////////////////////////////////////////////////////////////
 */
?>
<script type="text/javascript">
 //<![CDATA[
enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
Calendar._am = "AM"; // am/pm
Calendar._pm = "PM";

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "About the calendar";

Calendar._TT["ABOUT"] =
"DHTML Date/Time Selector\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
"\n\n" +
"Date selection:\n" +
"- Use the \xab, \xbb buttons to select year\n" +
"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
"- Hold mouse button on any of the above buttons for faster selection.";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"Time selection:\n" +
"- Click on any of the time parts to increase it\n" +
"- or Shift-click to decrease it\n" +
"- or click and drag for faster selection.";

Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
Calendar._TT["GO_TODAY"] = "Go Today";
Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
Calendar._TT["SEL_DATE"] = "Select date";
Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';

// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "Display %s first";

// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = "0,6";

Calendar._TT["CLOSE"] = "Close";
Calendar._TT["TODAY"] = "Today";
Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";

Calendar._TT["WK"] = "Week";
Calendar._TT["TIME"] = "Time:";



//]]>
</script>
<style type="text/css">
 .calendar {
    z-index: 9000 !important;
}
 </style>
<script type="text/javascript">

function SDEffect(element){
   //new Effect.toggle(element,'Slide', {duration:1});

   new Effect.toggle(element,'Slide', {duration:1});
   //new Effect.SlideDown('jobs_apply_form', { duration: 1.0 });

}

function SUEffect(element){
   //new Effect.toggle(element,'Slide', {duration:1});
   alert("test");
   new Effect.toggle(element,'Slide', {duration:1});
   //new Effect.SlideUp('jobs_apply_form', { duration: 1.0 });

}
 jQuery.noConflict();

  function showfancybox(){
  jQuery.fancybox.open([
            {
                fitToView: true,
                width: '70%',
                height: '70%',
                autoSize: true,
                closeClick: false,
                
                openSpeed: 'slow',
                transitionIn: 'elastic',
                content: jQuery('#jobs_form'),
                title         : 'Application Form',
                centerOnScroll : true,
                titleShow      : true,
                titlePosition  : 'inside',
                openMethod: 'stickyupIn',
                closeMethod: 'stickyupOut',
          }
        ]);
  }

</script>

<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "14a445d8-4bfe-482f-bc1c-63c3eac80a7d"}); </script>

<?php 
  $require_travel = array("Not Required", "required");
  $gender = array("Doesn't Matter", "Male", "Female");
?>
<?php foreach ($this->getItem() as $key => $item) : ?>
<div class="jobsdetail_main">
    <div class="job_heading"><h1><?php echo $item->getJobtitle(); ?></h1>
    <div class="apply_btn"><img border="0" width="115" vspace="5" height="30" src="<?php echo Mage::getBaseUrl('media').'jobs/applynow.gif' ?>" onclick="showfancybox();" ></div>
    </div>
    
    <div>
        <span class='st_sharethis_large' displayText='ShareThis'></span>
        <span class='st_facebook_large' displayText='Facebook'></span>
        <span class='st_twitter_large' displayText='Tweet'></span>
        <span class='st_linkedin_large' displayText='LinkedIn'></span>
        <span class='st_email_large' displayText='Email'></span>
        <!--<span class='st_fblike_large' displayText='Facebook Like'></span>
        <span class='st_plusone_large' displayText='Google +1'></span>-->
    </div>
    
    <div id="jobs_apply_form" style="display: none;">
           
        <div class="entry-edit">
                
  <h4 class=""><?php echo Mage::helper('jobs')->__('Application form') ?></h4>
                    
                
<div id="jobs_form" class="fieldset">
     
          <form id="fmejobsForm" action="<?php echo Mage::getUrl('jobs/index/formsubmit'); ?>" method="POST" enctype="multipart/form-data"> 
            <input type="hidden" name="job_id" value="<?php echo $item->getId(); ?>" />
          <ul class="form-list">
            <li class="fields">
              <div class="field">
                <label for="fullname"><?php echo Mage::helper('jobs')->__('Full Name') ?> <span class="required">*</span></label>
                <div class="input-box">
                  <input type="text" class=" input-text required-entry" value="" name="fullname" id="fullname" />
                </div>
               </div>
              <div class="field">
                <strong><label for="email"><?php echo Mage::helper('jobs')->__('Email') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                  <input type="text" class=" input-text required-entry validate-email" value="" name="email" id="email">
                </div>
                
              </div>
            </li>
            <li class="fields">
              <div class="field">
                <strong><label for="dob"><?php echo Mage::helper('jobs')->__('Date of Birth') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                <input type="text" class=" input-text required-entry validate-date" value="" name="dob" id="date-picker" />  
                <img src="<?php echo $this->getSkinUrl("images")."/grid-cal.gif";  ?>" alt="" class="v-middle" id="news_to_date_trig" title="Select Date of Birth" style="">
                
                </div>
              </div>
              <div class="field">
                <strong><label for="pob"><?php echo Mage::helper('jobs')->__('Place of Birth') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                  <input type="text" class=" input-text required-entry" value="" name="pob" id="pob"> 
                </div>
              </div>
            </li>
            <li class="fields">
              <div class="field">
                <strong><label for="nationality"><?php echo Mage::helper('jobs')->__('Nationality') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                  <input type="text" class=" input-text required-entry" value="" name="nationality" id="nationality">
                </div>
              </div>
              <div class="field">
                <strong><label for="telephone"><?php echo Mage::helper('jobs')->__('Telephone') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                  <input type="text" class=" input-text required-entry validate-number" value="" name="telephone" id="telephone">
                </div>
                
              </div>
            </li>
            <li class="fields">
              <div class="field">
                <strong><label for="fmejobs_address"><?php echo Mage::helper('jobs')->__('Address') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                  <textarea class=" input-text required-entry" value="" name="address" id="fmejobs_address"></textarea>
                <div class="input-box">
              </div>
              <div class="field">
                <strong><label for="fmejobs_zipcode"><?php echo Mage::helper('jobs')->__('Zip Code') ?> <span class="required">*</span></label></strong>
                <div class="input-box">
                  <input type="text" class=" input-text required-entry validate-postcode" value="" name="zipcode" id="fmejobs_zipcode">
                <div class="input-box">
              </div>
            </li>
            <li class="fields">
              <div class="field">
                <strong><label for="fmejobs_cv"><?php echo Mage::helper('jobs')->__('Upload CV') ?></label></strong>
                <div class="input-box">
                  <input type="file" class="" value="" name="cvfile" id="fmejobs_cv">
                <div class="input-box">
              </div>
              <div class="field">
                <div id="captcha">
                  <div class="input-box">
                    <input name="captacha_code" type="hidden" id="captacha_code" value="<?php echo $code=Mage::helper('jobs')->getNewrandCode(6)?>" />
                    <label for="image"><img style="display: block;" src="<?php echo Mage::helper('jobs')->getSecureImageUrl() ?>CaptchaSecurityImages.php?width=180&height=40&code=<?php echo $code?>" /></label><br/>
                    <div class="input-box">
                    <label for="security_code" class="required"><em>*</em><b><?php echo Mage::helper('jobs')->__('Security Code Message:') ?></b></label><br />
                    <input id="security_code" name="security_code" type="text" class=" input-text required-entry" /> <br />
                    <?php echo Mage::helper('jobs')->__('If you have difficulty in reading the image above then refresh your browser a few times until you see an image that is clear enough to copy.') ?>
                    </div>
                  </div> 
                </div>
              </div>
              </li>
              <li class="fields">
                <div class="field">
                  
                  <input class="button" type="submit" name="submit" value="Submit" />
                  
                </div>
              </li>
              </form>
              </div>
              </div>
        
    
    <script type="text/javascript">
    //<![CDATA[
    var editForm = new VarienForm('fmejobsForm', 'true');
    //]]>
    </script>
     
    </div>
    <div class="clear"></div>
    <div class="column-content">
    <div class="row">
            <div class="fields2">
                <strong><?php echo $this->__('Department:'); ?></strong>
            </div>    
            <div class="fields2">    
              <?php echo $item->getDepartmentName();  ?>
            </div>
    </div>    
     <div class="row">    
            <div class="fields2">
                <strong><?php echo $this->__('Job Type:'); ?></strong>
            </div>
            <div class="fields2">
               <?php echo $item->getJobtypeName();  ?>
            </div>
     </div>
      <div class="row">
          <div class="fields2">
                <strong><?php echo $this->__('Location:'); ?></strong>
          </div>
            <div class="fields2">
              <?php echo $item->getStoreName(); ?>
            </div>
       </div>        
       
       <div class="row">
      <div class="fields2">
         <strong><?php echo $this->__('Gender:'); ?></strong>
       </div>
       <div class="fields2">
        <?php echo $gender[$item->getGender()]; ?>
       </div>
       </div>
       
        <div class="row">
        <div class="fields2">
          <strong><?php echo $this->__('Total Positions:'); ?></strong>
        </div>
        <div class="fields2">
           <?php echo $item->getPositionsJobs(); ?>
         </div>
        </div>
         <?php if(trim($item->getMinQual()) != "" ): ?>
        <div class="row">
            <div class="fields2">
            <strong><?php echo $this->__('Minimum Qualification:'); ?></strong>
             </div>
            <div class="fields2">
                <?php echo $item->getMinQual(); ?>
             </div>
        </div>
           <?php endif; ?>   
      <?php if(trim($item->getCareerLevel()) != ""): ?>    
       <div class="row">
            <div class="fields2">
              <strong><?php echo $this->__('Career Level:'); ?></strong>
            </div>
            <div class="fields2">
                <?php echo $item->getCareerLevel(); ?>
            </div>
        </div>   
      <?php endif; ?> 
      <?php if(trim($item->getMinExp()) != ""): ?>
      <div class="row">
            <div class="fields2">
              <strong><?php echo $this->__('Minimum Experience:'); ?></strong>
             </div>
            <div class="fields2">
               <?php echo $item->getMinExp(); ?>
           </div>
        </div>      
     <?php endif; ?>
     <div class="row">
            <div class="fields2">
               <strong><?php echo $this->__('Require Travel:'); ?></strong>
            </div>
            <div class="fields2">
                 
                  <?php echo $require_travel[$item->getTravel()]; ?>
                
          </div>
      </div>        
        <div class="row">
            <div class="fields2">
               <strong><?php echo $this->__('Apply By:'); ?></strong>
            </div>
            <div class="fields2">
              
                <?php 
                         $atime_a = explode('-',$item->getApplyBy());
                         $atime = mktime(0,0,0,$atime_a[1], $atime_a[2], $atime_a[0]); 
                         echo date('F d, Y', $atime); 
                    ?>
                
           </div>
      </div>          
           <div class="row">
              <div class="fields2">
                <strong><?php echo $this->__('Posted:'); ?></strong>
              </div>
               <div class="fields2">
                 
                <?php 
                  $ctime_a = explode('-',$item->getCreateDates());
                  $ctime = mktime(0,0,0,$ctime_a[1], $ctime_a[2], $ctime_a[0]); 
                  echo date('F d, Y', strtotime($item->getCreateDates())); 
                        
                ?>
                
               </div>
            </div> 
    </div>
</div>


<div class="column-content2">
    <div class="des">
     <!--  <div class="right"> -->
	    <h2><?php echo $this->__('Job Descriptions');  ?></h2>
	    
        <?php echo Mage::helper('jobs')->getWysiwygFilter($item->getDescription());
        ?>
            <h2><?php echo $this->__('Skills Required');  ?></h2>
            <?php echo $item->getSkills();  ?>
      
	   <!--  </div> -->
        <div class="clear"></div>
    </div>
</div>
<div>
<script type="text/javascript">
        //<![CDATA[
            Calendar.setup({
                inputField: 'date-picker',
                ifFormat: '%m/%e/%y',
                showsTime: false,
                button: 'news_to_date_trig',
                align: 'Bl',
                singleClick : true
            });
        //]]>
</script>
<?php endforeach;  ?>     



