<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2016 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */
?>
<?php 
	if($website_json = $this->getWebsiteSnippets()) { 
		echo '<script type="application/ld+json">[' . json_encode($website_json) . ']</script>' . PHP_EOL; 
	} 
	if($organization_json = $this->getOrganizationSnippets()) { 
		echo '<script type="application/ld+json">[' . json_encode($organization_json) . ']</script>' . PHP_EOL;
	} 
	if($local_business_json = $this->getLocalBusinessSnippets()) { 
		echo '<script type="application/ld+json">[' . json_encode($local_business_json) . ']</script>' . PHP_EOL;
	} 
	if($web_page_snippets = $this->getWebPageSnippets()) { 
		echo '<script type="application/ld+json">[' . json_encode($web_page_snippets) . ']</script>' . PHP_EOL;
	} 
?>
