<?php
/**
 * @category   CLS
 * @package    UniversalAnalytics
 * @copyright  Copyright (c) 2015 Classy Llama Studios, LLC (http://www.classyllama.com)
 * @license    See LICENSE_CLS.txt for license details
 */
?>

<?php
// Put conversion ID in quotes if it's not a number
$_conversionId = $this->getConversionId();
$_conversionIdInt = (int) $_conversionId;
$_conversionIdConvertedString = (string) $_conversionIdInt;
if ($_conversionId != $_conversionIdConvertedString) {
    $_conversionId = '"' . $_conversionId . '"';
}
?>

<?php if($this->isEnabled()):?>
<!-- BEGIN GOOGLE ADWORDS CODE -->
<script language="JavaScript" type="text/javascript">
//<![CDATA[
var google_conversion_id = <?php echo $_conversionId ?>;
var google_conversion_language = "<?php echo $this->getLanguage() ?>";
var google_conversion_format = "1";
var google_conversion_color = "#FFFFFF";
var google_conversion_label = "<?php echo $this->getLabel() ?>";
<?php if ($this->getValue()): ?>
    var google_conversion_value = <?php echo $this->getValue() ?>;
<?php endif; ?>
//]]>
</script>
<script language="JavaScript" type="text/javascript" src="<?php echo $this->getConversionUrl() ?>"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" border="0" alt="" src="http://www.googleadservices.com/pagead/conversion/<?php echo $this->getConversionId() ?>/?value=<?php echo $this->getValue() ?>&label=<?php echo $this->getLabel() ?>&script=0">
    </div>
</noscript>
<!-- BEGIN GOOGLE ADWORDS CODE -->
<?php endif; ?>