<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.3.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
<?php if (count($_items)):?>
    <div class="box-title">
        <h2><?php echo $this->__('Customer Reviews') ?></h2>
    </div>
    <?php echo $this->getChildHtml('advancedreviews_proscons_filter') ?>
    <?php echo $this->getChildHtml('advancedreviews_ordering') ?>
    <?php echo $this->getChildHtml('toolbar') ?>
    <dl class="box-content" id="product-reviews-list">
    <?php foreach ($_items as $_review):?>
        <dt>
            <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->htmlEscape($_review->getTitle()) ?></a> <?php echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>
            <?php echo $this->getChild('advancedreviews_allmylink')->setReview($_review)->toHtml()  ?>
        </dt>
        <dd>
            <table class="data-table review-summary-table">
                <col />
                <col />
                <tbody>
                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                    <tr>
                        <th class="label"><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                        <td class="value">
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
            <p class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></p>
            <?php
                echo $this->getChild('advancedreviews_proscons_indicator')->setReviewId( $_review->getId() )->toHtml();
                echo $this->getChild('advancedreviews_recommend_indicator')->setReviewId( $_review->getId() )->toHtml();
                echo $this->getChild('advancedreviews_footer')->setReviewId( $_review->getId() )->toHtml();
            ?>
        </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">decorateGeneric($$('#product-reviews-list dd'), ['last']);</script>
    <?php echo $this->getChildHtml('toolbar') ?>
<?php endif;?>
<?php echo $this->getChildHtml('review_form') ?>
<?php echo $this->getChildHtml('advancedreviews_login') ?>
<?php echo $this->getChildHtml('advancedreviews_needbuy') ?>
</div>