.col-main>ol,.col-main>ul{font-size:0}
.col-main>ol li,.col-main>ul li{width:25%;display:inline-block;position:relative;margin:0 0 20px 0;text-align:center;font-size:14px;vertical-align:baseline;padding:5px;box-sizing:border-box}
.col-main>ol li h2,.col-main>ul li h2{min-height: 32px;text-transform:uppercase;margin:5px 0;font-size:14px;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif}
.col-main li .link-learn{background:#3399cc;display:block;padding:7px 15px;color:#FFFFFF;font-size:13px;text-transform:uppercase;max-width:120px;margin:5px auto}
.col-main li .link-learn:hover{background:#2e8ab8;text-decoration:none}
.col-main li .price-box p{display:inline-block;margin:0}
.col-main li .price{color:#3399cc;font-size:16px}
.col-main li .old-price .price{color:#a0a0a0;text-decoration:line-through}
.col-main li .btn-cart{background:#39c;display:inline-block;padding:7px 15px;border:0;color:#FFF;font-size:13px;line-height:normal;text-transform:uppercase;margin:10px 0 0 0}
.col-main li .btn-cart:hover{background:#2e8ab8;text-decoration:none}
.col-main li .price-label {display:none};
.col-main .toolbar{margin:10px 0 15px 0;border-bottom:1px solid #ccc;border-top:1px solid #ccc;background:#f4f4f4;padding:0 10px}
.pages{margin-bottom:10px}
.pages ol,pages ul {display:inline-block}
.pages li{display:inline-block;padding:0 5px}
.pager p{margin:9px 0 5px 0}
@media (max-width:780px){
.col-main>ol li,.col-main>ul li{width:33%}
}
@media (max-width:480px){
.col-main>ol li,.col-main>ul li{width:50%}
}