.catalog-product-view .col-main {font-size:0}
.product-img-box,.product-shop{width:50%;display:inline-block;margin-bottom:10px;padding:20px 0 0 20px;box-sizing:border-box;font-size:14px;vertical-align:top}
.product-shop{padding:20px 20px 0 0;margin-bottom:0}
.product-shop .description{margin-top:20px}
.product-img-box{float:right}
.btn-cart{background:#3399cc;display:inline-block;color:#FFFFFF;border:0;min-height:40px;line-height:40px;font-size:16px;padding:0px 30px;text-transform:uppercase}
.btn-cart:hover{background:#2e8ab8;color:#fff;text-decoration:none}
.price{color:#3399cc;font-size:24px}
.price-box{margin:0 0 15px 0;line-height:normal}
.price-box>p{display:inline-block;vertical-align:middle;margin:0}
.price-box .price-label{display:none}
.price-box .old-price .price {color:#a0a0a0;text-decoration:line-through;font-size:16px}

.additional-information{margin-top:20px}
.additional-information .title{font-weight:700}
.additional-information table{font-size:12px;border:1px solid #c9c7c7;border-collapse: collapse;text-align: left;margin-top: 10px}
.additional-information table th{border-right: 1px solid #c9c7c7;border-bottom: 1px solid #c9c7c7;background: #f4f4f4;padding: 5px 10px}
.additional-information table td{border-bottom: 1px solid #c9c7c7;padding: 5px 10px}
.additional-information table th.label{width:25%}
@media (max-width:640px){
.product-img-box,.product-shop{width:100%;display:block;padding:15px 0}
}