body{margin:0;padding:0;font-family:"Helvetica Neue",Verdana,Arial,sans-serif}
body,button,input,select,table,textarea{color:#636363;font-size:14px;line-height:1.5}
a{color:#3399cc;text-decoration:none}
a:hover{color:#2e8ab8;text-decoration:underline}
a:focus{outline:none;color:#143d52}
ol,ul{list-style:none;margin:0;padding:0}
.desktop{display:block}
@media (max-width:770px){
.desktop{display:none}
}

h1,.h1,h2,.h2,h3,.h3,h4,.h4,h5,.h5,h6,.h6{margin:0;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif;font-style:normal;line-height:1.2;text-transform:uppercase;font-weight:400;color:#636363;margin-bottom:0.5em}
h1,.h1{font-size:21px}
h2,.h2{font-size:18px}
h3,.h3{font-size:16px}
h4,.h4{font-size:14px}
h5,.h5{font-size:13px}
h6,.h6{font-size:12px}
.icon{background-image:url("<?php echo $this->getSkinUrl('images/plumrocket/pramp/icon_sprite.png') ?>"); background-repeat:no-repeat; text-indent:-9999px}
.page{position:relative;max-width:1260px;margin:0 auto;padding:10px 0}

.notice-inner{background:#676157;color:#e6e6e6;font-size:11px;line-height:14px;padding:14px 10px;box-sizing:border-box}
.notice-inner p{margin:0}
@media (min-width:771px){
.header-container{padding:0 30px;position:relative}
}

@media (max-width:771px){
	.notice-inner {padding: 4px 10px; font-size: 10px; line-height: 12px;}
}

.logo{display:block;padding:10px;max-width:272px}
h1.logo {padding: 0; margin-bottom: 0;}
.logo strong{display:none}

.nav-primary a{text-decoration:none;position:relative;display:block;color:#636363;line-height:30px;padding:3px;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif}
.nav-primary>li>a{padding:0 25px}
.nav-primary a:hover{color:#3399cc}
.nav-primary li{position:relative}
.nav-primary li.level1 a{border-bottom:1px solid #cccccc}
.nav-primary li.level1:last-child a{border-bottom:0}
.nav-primary li.level0 > a{text-transform:uppercase}

@media (min-width:771px){
#nav{display:block; border-bottom:1px solid #ededed; margin-top:15px}
a.level0{padding:0 25px}
li.level0,#nav a.level0{display:inline-block}
li.level0 ul{background:#FBFBFB;border:solid 1px #cccccc;position:absolute;left:0;top:30px;z-index:10;width:250px;padding-left:10px;padding-right:10px;display:none}
#nav li.level0:hover > ul{display:block}
}
@media (max-width:770px){
.skip-links li a:hover{background-color:#f4f4f4; text-decoration:none}
}

@media (max-width:640px){
}

.acc-cwrap {position:absolute;top:0;right:30px}
.acc-cwrap .skip-link .label{font-size:14px;text-transform:uppercase}
.acc-cwrap .skip-link{padding:0 10px;color:#636363;text-decoration:none;position:relative;display:inline-block}
.acc-cwrap .skip-link:hover{text-decoration:none;color:#3399cc}
.acc-cwrap .skip-cart .icon{background-position:0 -95px}
.acc-cwrap .skip-account .icon{background-position:4px -44px}
.acc-cwrap .skip-account:hover .icon{background-position:-46px -44px}
.acc-cwrap .skip-cart:hover .icon{background-position:-46px -44px;
}
.acc-cwrap .skip-cart:hover .icon{
background-position:-50px -95px;
}
.acc-cwrap .skip-link .links{background:#FBFBFB;border:solid 1px #cccccc;display:none;position:absolute;z-index:200;top:30px;left:0;width:200px;padding:5px 0}
.acc-cwrap .skip-link:hover .links{display:block}
.acc-cwrap .skip-link .links a{position:relative;display:block;padding:5px 10px;line-height:23px;text-align:center;color:#636363}

@media (max-width:770px){
.acc-cwrap{display:none}
}

.skip-links{clear:both;border-top:1px solid #EDEDED;position:relative;min-height:42px}
@media (min-width:771px){
.skip-links{border:0;display:none}
}

.skip-links .skip-link{float:left;width:33.3%;color:#636363;line-height:42px;text-align:center;border-bottom:1px solid #EDEDED}
.skip-links .skip-link a,.skip-links .skip-link>span{display:inline-block;line-height:42px;width:100%;color:#636363}
.skip-links .skip-link:hover{background:#EDEDED;color:inherit}
.skip-links .skip-link a:hover,.skip-links .skip-link>span:hover{text-decoration:none;cursor:pointer}
.skip-links .skip-link ul a,.skip-links .skip-link ol a{padding:0 15px 0 25px;text-align:left}
.skip-links .skip-link #nav,.skip-links .skip-link .links{display:none;position:absolute;z-index:100;background:#EDEDED;width:100%;left:0;top:42px}
.skip-links .skip-link:hover #nav,.skip-links .skip-link:hover .links{display:block}
.skip-links .skip-link .skip-nav .icon{background-position:4px 4px}
.skip-links .skip-link .skip-account .icon{background-position:4px -44px}
.skip-links .skip-link .skip-cart .icon{background-position:0 -95px}
@media (max-width:770px){
.skip-links .skip-link>span{border-right:1px solid #EDEDED}
#nav .nav-primary li.parent:hover > a:after{content:'';position:absolute;width:0;height:0;display:block;border-right:5px solid transparent;border-left:5px solid transparent;border-top:5px solid #cccccc;border-bottom:none;top:50%;left:10px;right:auto;margin-top:-5px}
#nav .nav-primary li.parent > a:after{content:'';position:absolute;width:0;height:0;display:block;border-top:5px solid transparent;border-bottom:5px solid transparent;border-left:5px solid #cccccc;border-right:none;top:50%;left:10px;right:auto;margin-top:-5px}
#nav .nav-primary li:hover > ul{display:block}
#nav li.level0 ul{display:none;padding-left:25px}
.nav-primary li.level0 li{padding:0 0 0 25px}
.skip-links .skip-link ul li a,.skip-links .skip-link ol li a{border-bottom:1px solid #cccccc}
.skip-links .skip-link ul li:last-child a:hover,.skip-links .skip-link ol li:last-child a:hover{background-color:#f4f4f4;text-decoration:none; }
.skip-links .skip-link:last-child{border-right:0}
}

.skip-link .icon{display:inline-block;width:30px;height:30px;vertical-align:middle}
.skip-link.skip-nav .icon{margin-right:3px}
@media (min-width:500px){
.skip-link .icon{margin-right:3px}
}

.breadcrumbs{overflow:hidden;margin:-15px 0 15px 0}
.breadcrumbs li{float:left;font-size:12px;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif;text-transform:uppercase}
.breadcrumbs a{float:left;color:#636363}
.breadcrumbs a:hover{color:#3399cc}
.breadcrumbs strong{color:#636363;font-weight:normal}
.breadcrumbs span{float:left;padding:0 7px}
@media (max-width:770px){
.breadcrumbs{display:none}
}

.main-container{padding: 30px;position: relative}
.main-container:before,.main-container:after{content:"";display:block;clear:both}
@media (max-width:640px){
.main-container{padding: 10px 15px;}
}

.footer-container{padding: 0 30px}
.footer{width:100%;border-top:1px solid #cccccc;padding-top:15px;text-align:center;font-size: 12px}
.footer address{border-top:1px solid #cccccc;text-align:center;width:100%;font-size:11px;margin-top:15px;padding:20px 0}
.footer li{display:inline-block;padding: 0 10px}
@media (max-width:640px){
.footer-container{padding:0 15px}
}
@media (-webkit-min-device-pixel-ratio:2),(min--moz-device-pixel-ratio:2),(-o-min-device-pixel-ratio:2/1),(min-device-pixel-ratio:2),(min-resolution:192dpi),(min-resolution:2dppx){
.icon{background-image:url("<?php echo $this->getSkinUrl('images/plumrocket/pramp/icon_sprite@2x.png') ?>");background-size:100px 1000px}
}