<ul class="ad">
    <li class="ad-item">
        <a href="#" class="ad-link">
            <div class="ad-details">
                <h4 class="ad-tagline">Short Intro Line</h4>
                <h3 class="ad-title">Primary Headline</h3>
                <span class="button button-small">Action Label</span>
            </div>

            <img class="ad-image" src="http://placehold.it/590x299" alt="#" />
        </a>
    </li>

    <li class="ad-item">
        <a href="#" class="ad-link">
            <div class="ad-details">
                <h4 class="ad-tagline">Short Intro Line</h4>
                <h3 class="ad-title">Primary Headline</h3>
                <span class="button button-small">Action Label</span>
            </div>

            <img class="ad-image" src="http://placehold.it/590x299" alt="#" />
        </a>
    </li>
</ul>
