<div class="set set--four">
    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/260x130" alt="#" />
        </a>
    </div>

    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/260x130" alt="#" />
        </a>
    </div>

    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/260x130" alt="#" />
        </a>
    </div>

    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/260x130" alt="#" />
        </a>
    </div>
</div>
