<div class="grid-box grid-box--left">
    <div class="grid-box-1-3">
        <img class="grid-box-image" src="http://placehold.it/376x192" alt="#" />
    </div>

    <div class="grid-box-2-3 grid-box-content">
        <h3 class="grid-box-title">Heading One</h3>

        <div class="grid-box-description std">
            <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor.</p>
        </div>

        <a href="#" class="button">Primary Action</a>
    </div>
</div>
