<div class="block" data-toggle="hide">
    <div class="block_title" data-toggle-trigger>
        <h3>Lorem ipsum dolor sit amet?</h3>
    </div>

    <div class="block_content" data-toggle-target>
        <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>

        <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>
    </div>
</div>
