<a href="#" class="hero hero--center hero--cta">
    <div class="hero-image">
        <img src="http://placehold.it/1200x500/d0d0d0/c0c0c0" alt="#" />
    </div>

    <div class="hero-content-wrapper">
        <div class="hero-content">
            <div class="hero-title-pre">Write A Subtitle</div>
            <h1 class="hero-title">And Primary Title</h1>
            <div class="button button-large" href="#">Call To Action</div>
        </div>
    </div>
</a>
