<ul class="pattern-navigation">
    <li><a href="{{store direct_url="nucleus-elements-interactive"}}">Interactive Elements</a></li>
    <li><a href="{{store direct_url="nucleus-elements-presentational"}}">Presentational Elements</a></li>
    <li><a href="{{store direct_url="nucleus-elements-hero"}}">Hero Banners</a></li>
    <li><a href="{{store direct_url="nucleus-elements-mini"}}">Mini Elements</a></li>
</ul>