<div class="accordion">
    <div class="accordion-sections">
        <section id="accordion-section-one" class="accordion-section">
            <h3 class="accordion-header">Section 1</h3>

            <article class="accordion-content">
                <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>

                <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>
            </article>
        </section>

        <section id="accordion-section-two" class="accordion-section">
            <h3 class="accordion-header">Section 2</h3>

            <article class="accordion-content">
                <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>

                <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>
            </article>
        </section>

        <section id="accordion-section-three" class="accordion-section">
            <h3 class="accordion-header">Section 3</h3>

            <article class="accordion-content">
                <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>

                <p>Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu.</p>
            </article>
        </section>
    </div>
</div>