<div class="set set--three">
    <div class="set-item">
        <h3 class="set-title">First Title</h3>
        <p class="set-description">Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor.</p>
        <a class="button" href="#">Action</a>
    </div>

    <div class="set-item">
        <h3 class="set-title">Second Title</h3>
        <p class="set-description">Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor. Curabitur vulputate, ligula lacinia scelerisque tempor.</p>
        <a class="button" href="#">Action</a>
    </div>

    <div class="set-item">
        <h3 class="set-title">Third Title</h3>
        <p class="set-description">Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor.</p>
        <a class="button" href="#">Action</a>
    </div>
</div>
