<div class="set set--three">
    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/360x180" alt="#" />
        </a>
    </div>

    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/360x180" alt="#" />
        </a>
    </div>

    <div class="set-item">
        <a href="#">
            <img src="http://placehold.it/360x180" alt="#" />
        </a>
    </div>
</div>
