<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.3.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $collection = $this->getCollection(); ?>
<?php if($collection):?>
    <?php if($collection->getSize()):?>
        <?php foreach ($collection as $_review):?>
            <div class="review-header">
                <h4 id="review-title">
                    <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->htmlEscape($_review->getTitle()); ?>:</a> <?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
                </h4>
                <h5 class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt(), 'long')) ?></h5>
            </div>
            <?php echo (!$this->getRequest()->getParam('customerId'))?$this->getChild('advancedreviews_allmylink')->setReview($_review)->toHtml():''?>
            <?php $_votes = $this->getRatingVotes($_review->getId());?>
            <?php if (count($_votes)): ?>
                <div class="ratings-table">
                    <?php foreach ($_votes as $_vote): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <div id="review-content">
                <div id="recommendation"><?php echo $this->getChild('advancedreviews_recommend_indicator')->setReviewId( $_review->getId() )->toHtml(); ?></div>
                <div id="review-body">
                    <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
                    <?php echo $this->getChild('advancedreviews_proscons_indicator')->setReviewId( $_review->getId() )->toHtml(); ?>
                </div>
            </div>
            <?php echo $this->getChild('advancedreviews_footer')->setReviewId( $_review->getId() )->toHtml(); ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo $this->__('No reviews have been found');?>
    <?php endif;?>
<?php endif;?>
