<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.3.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="product-view" id="need-to-modyfiy">
<?php echo  $this->getChildHtml('advancedreviews_stdreviews'); ?>
</div>
<style type="text/css">
    .modifyed-product-view {
        border-top: none !important;
    }
    .modifyed-main-col {
        padding-top: 0px !important;
    }
</style>
<script type="text/javascript">
    try{
        $('need-to-modyfiy').addClassName('modifyed-product-view');
        $('need-to-modyfiy').parentNode.addClassName('modifyed-main-col');
    } catch(e){
        console.log(e.message);
    }
</script>